# https://github.com/ankurk91/phpunit-travis-ci-coveralls-example/blob/master/.travis.yml

language: php

os: linux

sudo: false

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - hhvm

# Tell Travis CI to monitor only 'master' branch
branches:
  only:
  - master
  - 1.0

matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true


# Composer package installation
install:
  # Install composer packages, will also trigger dump-autoload
  - travis_retry composer install --prefer-source --no-interaction --dev --ignore-platform-reqs
  # Install coveralls.phar
  - wget -c -nc --retry-connrefused --tries=0 https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar
  - chmod +x coveralls.phar
  - php coveralls.phar --version

# Create a storage folder for Coverage report
before_script:
  - mkdir -p build/logs
  - ls -al

script:
  - phpunit --coverage-clover build/logs/clover.xml
  - composer phpstan


after_success:
  # Submit coverage report to Coveralls servers, see .coveralls.yml
  - travis_retry php coveralls.phar -v
  # Submit coverage report to codecov.io
  - bash <(curl -s https://codecov.io/bash)

# Configure email notifications
notifications:
  email:
    on_success: never
    on_failure: always


# You can delete cache using travis-ci web interface
cache:
  directories:
    - vendor
    - $HOME/.cache/composer